### ISSUE TITLE
프로필씬 및 유저 데이터 관련 버그

### ISSUE THREAD

**Issue by seong0929** [SeoulTechTCPGame/block-it#101]
- 프로필씬
  - 해당 씬에 들어가면 아래와 같은 버그가 나옵니다.
  - ![image](https://github.com/SeoulTechTCPGame/block-it/assets/50050003/b77dc576-33c1-4566-b578-be17cd52e18f)
- 로딩씬
  - AuthManager의 저장 기능을 아래와 같이 수정하여 작동이 되도록 하였습니다.
  - 유저 정보 저장을 처음부터 관리하도록 하였습니다.
  - StartGame 에서 Null인지 확인을 하는 데, 로그인이 이미 되어 있는 상태로 뜹니다.
  - 로그인된 상태와 로그인이 되지 않은 상태 테스트가 힘듭니다.
<pre>
<code>
using UnityEngine;

// 유저 정보
public class UserData : MonoBehaviour
{
    public static UserData instance;
    private string _userName;
    private string _userId;

    private void Awake()
    {
        if (instance == null)
        {
            instance = this;
        }
        else if (instance != this)
        {
            Destroy(instance.gameObject);
        }
        DontDestroyOnLoad(this.gameObject);
    }
    /** load login info **/
    public void LoadUserInfo()
    {
        _userName = PlayerPrefs.GetString("User_Display_Name", null);
        _userId = PlayerPrefs.GetString("User_Id", null);
    }
    /** save login info **/
    public void SaveUserInfo()
    {
        PlayerPrefs.SetString("User_Display_Name", _userName);
        PlayerPrefs.SetString("User_Id", _userId);
    }
}
</code>
</pre>
<pre>
<code>
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;

// 로그인 여부 판단하여, 시작 씬의 UI를 보여주는 클래스
public class StartGame : MonoBehaviour
{
    [SerializeField] float _TouchTimeout = 1f;  // 대기 시간
    [SerializeField] GameObject Canvas;

    private float _timer;   // 시간 지났는 지 여부
    private bool _loggedIn = false; //로그인 여부
    private GameObject _signUpButton;   //로그인 버튼
    private GameObject _guestButton;    //게스트 모드 버튼
    private GameObject _developButton;  //개발자 모드 버튼으로 ToDo: 삭제 예정

    private void Start()
    {
        UserData.instance.LoadUserInfo();
        if (PlayerPrefs.GetString("User_Display_Name") != null)
        {
            _loggedIn = true;
        }

        _developButton = Canvas.transform.Find("Develop").gameObject;
        _signUpButton = Canvas.transform.Find("Sign In").gameObject;
        _guestButton = Canvas.transform.Find("Guest").gameObject;

        ButtonsVisibility();    // 버튼 보이는 지 여부 판단
        _developButton.GetComponent<Button>().onClick.AddListener(MoveHomeScene);   // 개발자용으로 ToDo: 삭제 예정
    }
    private void Update()
    {
        _timer += Time.deltaTime;
        if (_loggedIn && ((Input.touchCount > 0 && Input.GetTouch(0).phase == TouchPhase.Began) || _timer >= _TouchTimeout))
            // 로그인이 되어 있으면서 화면을 터치했거나 시간이 지나면 자동으로 화면 전환
        {
            MoveHomeScene();
        }
    }
    private void ButtonsVisibility()
    {
        if (_loggedIn == false)
        {
            _signUpButton.SetActive(!_loggedIn);
            _guestButton.SetActive(!_loggedIn);

            _signUpButton.GetComponent<Button>().onClick.AddListener(MoveSignUpScene);
            _guestButton.GetComponent<Button>().onClick.AddListener(MoveHomeScene);
        }
    }
    private void MoveSignUpScene()
    {
        SceneManager.LoadScene("Auth");
    }
    private void MoveHomeScene()
    {
        SceneManager.LoadScene("Home");
    }
}
</code>
</pre>

**Comment by Lee-Hyeong-Jin** [comment]
@az0t0 참조 객체가 존재하지 않는다고 떠서 임시적으로 참조 관계를 만들어 해결했습니다
