### ISSUE TITLE
프로필 UI

### ISSUE THREAD

**Issue by junnie082** [SeoulTechTCPGame/block-it#11]
[피그마](https://www.figma.com/file/axcqNlMNnMknrpX1aesM97/Quoridor?node-id=0%3A1&t=vLyf2wqSAOD6NTIx-1)

- ~~본인의 등급과 랭크를 표시 (브론즈, 실버, 골드, 플래티넘, 다이아, 루비, 마스터)~~
  - 브론즈: 상위 100%
  - 실버: 상위 70%
  - 골드: 상위 50%
  - 플래티넘: 상위 20%
  - 다이아: 상위 10%
  - 루비: 상위 5%
  - 마스터: 상위 1%

- [x] 지금까지 플레이한 게임의 수와 승률을 표시
- [x] My Profile 에서 본인의 사진과 아이디를 변경할 수 있음
- ~~프로필 사진 주변에 랭크에 맞는 색띠가 있음~~
- ~~승점 계산식, 연승/연패 계산식~~

![Image](https://user-images.githubusercontent.com/88719152/235483893-be63ac6d-3a94-48cd-851b-9f8417ae4a87.png)
![Image](https://user-images.githubusercontent.com/88719152/235483892-86a3dcae-8417-4766-97f0-85cc7b9ffd48.png)
![Image](https://user-images.githubusercontent.com/88719152/235483891-b4061932-32d8-4bf1-bd4d-5af5c60a0721.png)
![Image](https://user-images.githubusercontent.com/88719152/235483895-eea8b1b1-fe36-45bd-b904-49a751bb5a36.png)

**Comment by junnie082** [comment]
- [ ] 회원가입 버튼 클릭 시 회원가입 화면으로 이동

**Comment by seong0929** [comment]
랭크 시스템 폐기
