### ISSUE TITLE
Class Diagram 및 FSM 논의

### ISSUE THREAD

**Issue by junnie082** [SeoulTechTCPGame/block-it#112]
## Class Diagram

https://drive.google.com/drive/my-drive

<img width="718" alt="스크린샷 2023-09-17 오후 3 29 07" src="https://github.com/SeoulTechTCPGame/block-it/assets/88719152/9a8308ce-8f2f-4a1e-912f-7eb34cacc1b1">

**Comment by junnie082** [comment]
https://drive.google.com/drive/my-drive
<img width="793" alt="스크린샷 2023-09-17 오후 4 39 39" src="https://github.com/SeoulTechTCPGame/block-it/assets/88719152/462cf0b5-54a6-4c27-86ef-77b6904d3d27">

**Comment by seong0929** [comment]
![image](https://github.com/SeoulTechTCPGame/block-it/assets/50050003/0612d7fb-166f-4e1e-8997-6e4493ae4ea7)
|이동|내용|
|--|--|
|시작/종료 -> 로그인||
|시작/종료 -> 로그인||
|시작/종료 -> 로그인||

**Comment by junnie082** [comment]
클래스 다이어그램에 CommonScript를 추가, FSM까지 수정하여 리드미 작성 완료하였습니다.
