### ISSUE TITLE
현재 develop 브랜치에서 발생하는 인게임 버그

### ISSUE THREAD

**Issue by az0t0** [SeoulTechTCPGame/block-it#127]
# 개요
아래의 버그는 `WifiMode`, `FriendMode`와 상관없이 발생하는 버그이며, 해당 버그로 인해 최신 커밋 병합 이후 테스트가 불가능한 상황이니 빠른 해결을 부탁드립니다.

## 플레이 시작 시 Expel 버튼 NullReferenceException 발생
![image](https://github.com/SeoulTechTCPGame/block-it/assets/113516890/25911bd1-9675-4060-9726-0fb962c1ccdf)
Expel 버튼이 항상 표시되어 상대방을 언제든지 추방할 수 있게 됐습니다.

## History 기능이 처음부터 활성화되어 관련 UI가 표시됨
![image](https://github.com/SeoulTechTCPGame/block-it/assets/113516890/85f16456-673c-4a0c-81f5-4f708939d044)
해당 현상으로 인해 게임 플레이가 불가능한 것으로 추정됩니다.

## _gameMode을 WifiMode로 설정해도 FriendMode로 동작
Search Scene에서 대전을 서로 수락한 후 `_ms.ToLocalPlayMultiWifi()`를 사용하여 Scene을 이동해도 `FriendMode`와 같은 UI로 동작합니다.

**Comment by seong0929** [comment]
![image](https://github.com/SeoulTechTCPGame/block-it/assets/50050003/7a2b5b89-9a7b-4159-8d99-68709bfbd79c)
- Expel Button에 맵핑이 안되서 생긴 문제인 듯 싶습니다.
- 해당 버그로 인해 LocalPaly씬에서 오류가 발생하여 플레이를 할 수 없습니다.

<pre>
<code>

    private void SetTurn(EPlayer ePlayer)
    {
        ExpelButton.SetActive(false);      // 해당 라인 MatchManager.cs의 250번째 줄에서 오류가 발생하고 있습니다.
---
    }
</code>
</pre>
