### ISSUE TITLE
모드 선택 버튼 텍스트 잘못 설정됨

### ISSUE THREAD

**Issue by KimDa99** [SeoulTechTCPGame/block-it#129]
![image](https://github.com/SeoulTechTCPGame/block-it/assets/91198933/4d29dd79-2816-41d3-933c-9cabaf73fbd1)

온라인 플레이와 로컬 플레이 버튼이 바뀌어져 있습니다.

**Comment by seong0929** [comment]
[수정 완료하여 머지 하였습니다.](https://github.com/SeoulTechTCPGame/block-it/pull/139)
