### ISSUE TITLE
모바일 게임 플레이 화면 UI

### ISSUE THREAD

**Issue by seong0929** [SeoulTechTCPGame/block-it#134]
- 모바일 게임 플레이 씬으로 접근 시 불필요한 UI가 등장합
![KakaoTalk_20231101_151436657](https://github.com/SeoulTechTCPGame/block-it/assets/50050003/604f1da3-3836-45d6-8b27-7f6ff71e5ded)

**Comment by KimDa99** [comment]
https://github.com/SeoulTechTCPGame/block-it/pull/140
