### ISSUE TITLE
게임 플레이 터치 문제

### ISSUE THREAD

**Issue by seong0929** [SeoulTechTCPGame/block-it#138]
- 모바일 터치가 되지 않습니다.
1. Pawn의 좌우만 선택 가능, 상하 터치가 안됨.
2. Plank는 아예 위치를 선택할 수 없음.
![image](https://github.com/SeoulTechTCPGame/block-it/assets/50050003/b6fe4bab-8de0-49ac-bd61-929c292c5379)

**Comment by KimDa99** [comment]
https://github.com/SeoulTechTCPGame/block-it/pull/140
