### ISSUE TITLE
플랭크, 보드판 오브젝트, UI (움직임이 필요한 UI)

### ISSUE THREAD

**Issue by junnie082** [SeoulTechTCPGame/block-it#19]
- [x] 플레이어를 이동시키거나 플랭크를 두는 행동을 나타내는 버튼 두 개
- [x] 상대방과 나에게 남은 플랭크의 개수가 각각 표시
- [x] 보드판 배치
- [x] 플레이어를 이동시키거나 플랭크를 두는 행동을 나타내는 버튼 두 개
![Image](https://user-images.githubusercontent.com/88719152/235484882-906b4e1d-6724-4fc8-ae33-b616b7757c87.png)
![Image](https://user-images.githubusercontent.com/88719152/234329473-4876077c-e2ce-4b91-9c3a-be55ec969319.png)
![Image](https://user-images.githubusercontent.com/88719152/234329687-5b496a9e-986f-42c1-b25d-e2fe6ef8378c.png)

**Comment by KimDa99** [comment]
DONE
