### ISSUE TITLE
튜토리얼 대본

### ISSUE THREAD

**Issue by junnie082** [SeoulTechTCPGame/block-it#2]
[피그마 영어 버전](https://www.figma.com/file/axcqNlMNnMknrpX1aesM97/Quoridor?node-id=0-1&t=lLBbyri6n46sUDaj-0)
[피그마 한국어 버전](https://www.figma.com/file/4Mx5Zph4ScWQ7ioP4QtL9g/Quoridor_Korean_Version?t=JkfQx2jyWT84Iu31-0)

Quoridor 에서는 세 가지 모드를 지원합니다!
지금 함께 있는 사람과 플레이할 수도 있고, 전 세계 숨어 있는 실력자들과 플레이할 수도 있고, 인공지능과 플레이할 수도 있습니다.

쿼리도는 1997년 멘사셀렉트 추상전략게임으로써 공간지각력을 향상 시키며 두뇌 개발을 하는 데에 좋습니다. 꾸준히 연습하고 플레이 하다 보면 어느새 나의 사고력 또한 쑥쑥 자라나 있겠죠!

Play with friend 는 오프라인 친구들과 플레이할 수 있도록 만들어진 모드입니다. 친구들 중에 누가 쿼리도를 가장 잘하는 지 겨루어 보세요!
Play with others 는 전세계 실력자들과 플레이할 수 있도록 만들어진 모드입니다. 숨겨진 고수를 꺾고 포인트를 얻어 점수와 랭크를 갱신하여 세계 최고 마스터에 도전해 보세요!
Play with AI 는 인공지능과 플레이할 수 있도록 만들어진 모드입니다. easy, medium, hard 난이도를 선택할 수 있으며, 다른 사람들과 플레이하기 전에 미리 연습할 수 있습니다.

## 구성

- 메인 보드판 (9x9)
- 플레이어 두 개 (원래의 쿼리도 게임에서는 4인 플레이 가능하지만, 우리가 만들 프로그램은 2인 플레이만 가능합니다.)
- 플랭크 (각 플레이어마다 10개씩)

## 규칙

[쿼리도의 규칙(위키백과)](https://namu.wiki/w/쿼리도)

- 쿼리도는 본인의 플레이어를 상대 진영으로 먼저 보내면 이기는 게임입니다. 여기서 상대 진영이란, 본인 플레이어의 시작점을 기준으로 상대의 시작점인 마지막 줄을 의미합니다. 
- 플레이어는 턴마다 플레이어를 이동시키거나 나무 판자를 놓는 동작 중에 한 가지를 선택할 수 있습니다. 
- 플레이어는 상,하,좌,우 중 하나의 이동 방향을 선택할 수 있습니다. 
- 플랭크는 보드판의 칸을 두 개 차지합니다. 한 칸만 차지하거나 보드판의 경계를 넘어 판자를 둘 수 없습니다. 
- 플레이어끼리 만나면, 플레이어는 상대 플레이어를 뛰어 넘을 수 있습니다. 

### 주의할 점

[피그마](https://www.figma.com/file/t7zt3aqK1ccUGSmFl3mR0V/Quoridor_cases?node-id=0%3A1&t=xFhSqj9ZZDTohd5T-1)

1. 상대를 뛰어 넘어 이동하려고 하는 방향에 이미 나무 판자가 존재할 때는 각 상황마다 플레이어가 이동할 수 있는 곳이 정해져 있습니다. 

![Image](https://user-images.githubusercontent.com/88719152/233144378-b341f1ee-ec1b-4810-9c5d-8268055ba7f6.png)
![Image](https://user-images.githubusercontent.com/88719152/233144376-2bf2b2ae-210c-433d-b544-2e52c47f1c71.png)
![Image](https://user-images.githubusercontent.com/88719152/233144375-40b0a5b2-b7e9-4e61-ac03-c5d93e50f194.png)
![Image](https://user-images.githubusercontent.com/88719152/233144380-58c561b1-6686-4e57-b5f2-b47a915afabc.png)
![Image](https://user-images.githubusercontent.com/88719152/233144377-4845b1b3-cb6d-479c-84ca-e2e1b46154a4.png)
![Image](https://user-images.githubusercontent.com/88719152/233144379-974002da-1596-4604-8324-2a09eb65ff83.png)

2. 각 플레이어가 상대 진영에 도달할 수 있는 길이 최소 한 개 이상 있어야 합니다. 즉, 나무 판자로 플레이어의 모든 진로를 막을 수는 없습니다.

![Image](https://user-images.githubusercontent.com/88719152/233145624-d9764997-4222-4e1b-a927-23c24808512e.png)

**Comment by seong0929** [comment]
- [튜토리얼 todo](https://github.com/junnie082/block-it/issues/10)는 영어로 제작되어 있음
- 한국어도 위 형식에 맞게 수정해주세요
