### ISSUE TITLE
GameLogic - GetMoveablePawnCoords() 에러

### ISSUE THREAD

**Issue by KimDa99** [SeoulTechTCPGame/block-it#50]
moveableCoord가 pawn의 상하좌우+ pawn위치 리턴

- 현재 Pawn 위치도 moveableCoord에 포함됨 -> 자기 자신 위치 제외하기
- pawn이 가장자리에 있을 때, 범위가 넘어가는  경우에도 리턴 - 제외하기

**Comment by KimDa99** [comment]
- 건너뛰기 안됨

**Comment by KimDa99** [comment]
추가 발견시 고침 필요

**Comment by junnie082** [comment]
- [ ] 두 플레이어가 만났을 때 건너뛰기 preview 가 없음
- [ ] 두 플레이어가 만난 후에, 상대 플레이어가 있던 자리에 preview 가 다시 생기지 않음
- [ ]  validCoords 안에 자신의 좌표도 포함되면 안됨
- [ ] pawn 이 가장 자리에 있을 때 보드판 밖에 있는 좌표는 제외
