### ISSUE TITLE
브랜치 및 커밋 전략

### ISSUE THREAD

**Issue by junnie082** [SeoulTechTCPGame/block-it#6]
필요 시 comment 로 추가 부탁드립니다.

# 브랜치 전략
- main: 안정적인 브랜치로, 편집할 수 없고 오직 PR 만 받는 가장 큰 중추 브랜치.
- develop: 개발 중추 브랜치로 feature 브랜치 등을 develop 브랜치로 합침.
- feature: 기능 개발 브랜치.
  - feature 는 앞에 develop 을 붙여서 사용.
- hotfix: 브랜치가 삭제되었을 때 수정 및 리팩토링을 위한 브랜치.

ex) develop-AI

# 커밋 전략
- feat: 기능 추가 및 수정
- fix: 버그 수정
- add: 필요한 자료 추가
- chore: 잡일, 허드렛일
- refactor: 리팩토링
- test: 테스트 코드 작성 및 테스트

**Comment by seong0929** [comment]
영어를 기준으로 합니다

**Comment by junnie082** [comment]
브랜치 이름은 대문자로 시작합니다. (develop, main 제외. 예시: develop-Option)
