### ISSUE TITLE
Pawn Preview 에러

### ISSUE THREAD

**Issue by KimDa99** [SeoulTechTCPGame/block-it#63]
# 첫 번째 Pawn Preview 에러
1. Pawn의 좌표가 (0,0) or (8,0)일 때
pawn 버튼을 누르면 튕김 - 아마 존재하지 않는 범위외를 요청해서 그런 듯

![image](https://github.com/SeoulTechTCPGame/block-it/assets/91198933/83e774cb-9de7-40fe-bbd8-f0cc74b342ec)

errorMessage:
NullReferenceException: Object reference not set to an instance of an object
BoardManager.showMoveablePawns () (at Assets/Scenes/PlayScene/UI/BoardManager.cs:89)
UnityEngine.Events.InvokableCall.Invoke () (at <6c9b376c3fca40b787e8c1a2133bf243>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <6c9b376c3fca40b787e8c1a2133bf243>:0)
PlayerButtons.onPawnButtonClicked () (at Assets/Scenes/PlayScene/UI/PlayerButtons.cs:94)
UnityEngine.Events.InvokableCall.Invoke () (at <6c9b376c3fca40b787e8c1a2133bf243>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <6c9b376c3fca40b787e8c1a2133bf243>:0)
UnityEngine.UI.Button.Press () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Button.cs:70)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Button.cs:114)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:57)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:272)
UnityEngine.EventSystems.EventSystem:Update() (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventSystem.cs:530)

3. Pawn의 좌표 y =8일때

위로가는 방향만 표시됨

![image](https://github.com/SeoulTechTCPGame/block-it/assets/91198933/81d78145-7f7f-458b-a3dd-194d13252157)

**Comment by junnie082** [comment]
# 두 번째 Pawn Preview 에러

<img width="1440" alt="스크린샷 2023-07-13 오후 4 00 27" src="https://github.com/SeoulTechTCPGame/block-it/assets/88719152/163ed87c-8772-493c-8ded-21e29fb31a81">

위와 같은 상황에서 Pawn 1 양 옆에 preview 가 떠야 하는데 Pawn 2 의 동쪽과 서쪽에 preview 가 뜨고 있음.

# 세 번째 Pawn Preview 에러 

<img width="1440" alt="스크린샷 2023-07-13 오후 4 31 47" src="https://github.com/SeoulTechTCPGame/block-it/assets/88719152/d8ed6614-a94c-46ca-942f-0fe953d59a59">

Pawn 2 가 오른쪽 코너에 가게 되었을 때, preview 가 북쪽과 서쪽에 떠야 함에도 불구하고 북쪽 preview 만 정상 작동함.

# 네 번째 Pawn Preview 에러

<img width="1440" alt="스크린샷 2023-07-13 오후 4 32 05" src="https://github.com/SeoulTechTCPGame/block-it/assets/88719152/bf5aa4b5-c1cd-4f0d-a117-4aecb06cb7f2">

Pawn 2 가 오른쪽 사이드에 가게 되었을 때, preview 가 북쪽, 서쪽, 남쪽에 떠야 함에도 불구하고 서쪽의 preview 가 정상 작동되고 있지 않음


# 다섯 번째 Pawn Preview 에러

<img width="1440" alt="스크린샷 2023-07-13 오후 4 32 25" src="https://github.com/SeoulTechTCPGame/block-it/assets/88719152/14784319-e969-4c11-bae9-2f45ff0f4da2">


<img width="1084" alt="스크린샷 2023-07-13 오후 4 48 35" src="https://github.com/SeoulTechTCPGame/block-it/assets/88719152/2f82ac6d-88ae-42e7-880b-a4e6dca9e079">




Pawn 1 이 왼쪽 코너에 다다르게 되면, Pawn 1 preview 를 선택하고 put 버튼을 눌러도 아무 일이 발생하지 않음 (혹시 마지막 row 에 다다르게 되어 Pawn 1 의 상태가 Win 이 되어서 그런 것인지 확인 부탁)

# 여섯 번째 Pawn Preview 에러 

<img width="1440" alt="스크린샷 2023-07-13 오후 4 37 21" src="https://github.com/SeoulTechTCPGame/block-it/assets/88719152/20aef854-8aa5-41aa-95f0-9b9fc4955756">

<img width="1100" alt="스크린샷 2023-07-13 오후 4 50 45" src="https://github.com/SeoulTechTCPGame/block-it/assets/88719152/7c0fea81-0e6f-43bf-a814-55214d6813b0">



Pawn 2 (빨간색 Pawn)가 저 위치에 다다르면, preview 중 하나를 선택하고 put 을 눌러도 pawn 이 이동하지 않음

**Comment by junnie082** [comment]
해결했습니다.
