### ISSUE TITLE
Error - placing planks

### ISSUE THREAD

**Issue by KimDa99** [SeoulTechTCPGame/block-it#68]
플랭크를 놓는 과정에서 에러가 발생합니다.
수정 바랍니다.

- 상황
 플랭크를 놓고 다음 턴이 되었을때 ,  gameLogic의 SetPlank > bfs.IsThereAtLeastOneWay 에서 에러발생

- Error Log
![image](https://github.com/SeoulTechTCPGame/block-it/assets/91198933/d1d31975-2bfe-44c2-ba2e-5daaba0e198d)
"IndexOutOfRangeException: Index was outside the bounds of the array.
BFS.IsThereAtLeastOneWay (Pawn pawn) (at Assets/Scenes/PlayScene/Script/BFS.cs:25)
GameLogic.SetPlank (Plank plank) (at Assets/Scenes/PlayScene/Script/GameLogic.cs:226)
MatchManager.setTurn (EPlayer ePlayer) (at Assets/Scenes/PlayScene/Script/MatchManager.cs:87)
MatchManager.nextTurn () (at Assets/Scenes/PlayScene/Script/MatchManager.cs:58)
UnityEngine.Events.InvokableCall.Invoke () (at <6c9b376c3fca40b787e8c1a2133bf243>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <6c9b376c3fca40b787e8c1a2133bf243>:0)
PlayerButtons.OnPutButtonClicked () (at Assets/Scenes/PlayScene/UI/PlayerButtons.cs:85)
UnityEngine.Events.InvokableCall.Invoke () (at <6c9b376c3fca40b787e8c1a2133bf243>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <6c9b376c3fca40b787e8c1a2133bf243>:0)
UnityEngine.UI.Button.Press () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Button.cs:70)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Button.cs:114)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:57)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:272)
UnityEngine.EventSystems.EventSystem:Update() (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventSystem.cs:530)
"

**Comment by KimDa99** [comment]
당장 보이는 문제
1. row, col, coordinate 범위 처리 안 되어 있음. 
2. gameLogic을 새로 생성함...

**Comment by junnie082** [comment]
[싱글톤 패턴](https://dlemrcnd.tistory.com/8)
Singleton 패턴은 단 하나의 객체를 생성해서 사용하는 디자인 패턴이다.
단, 컴포넌트 하나만 있어야 한다.

```C#
public static 클래스 이름 instance;

private void Awake()
{
    instance = this;
}

// 함수 호출 사용시
클래스이름.instance.함수();
```
