### ISSUE TITLE
Firebase Login package

### ISSUE THREAD

**Issue by Lee-Hyeong-Jin** [SeoulTechTCPGame/block-it#79]
로그인을 위한 패키지 설정 방법(.gitignore 처리 되어 있어 각자 설정해야함)

<img width="722" alt="스크린샷 2023-07-26 오전 12 16 58" src="https://github.com/SeoulTechTCPGame/block-it/assets/114052845/1f63f38f-67b5-46d6-82c3-66ffcb87ce2f">
<img width="988" alt="스크린샷 2023-07-26 오전 12 17 41" src="https://github.com/SeoulTechTCPGame/block-it/assets/114052845/5bd24a99-e4b5-4bd4-a309-519757f0fd53">
<img width="988" alt="스크린샷 2023-07-26 오전 12 18 13" src="https://github.com/SeoulTechTCPGame/block-it/assets/114052845/34c7bc24-6189-48d3-a62c-e72ce804a55e">

설치 받은 json및 plist파일은 Assets폴더에 옮기면 됩니다!!

sdk설치 파일은 카카오톡으로 보내드리겠습니다.

<img width="988" alt="image" src="https://github.com/SeoulTechTCPGame/block-it/assets/114052845/12282873-4099-4cfd-9f95-4bf36b217795">

<img width="988" alt="image" src="https://github.com/SeoulTechTCPGame/block-it/assets/114052845/d7fc4d99-8eeb-4fdd-b2be-681485ff9a64">

import 누르시면 패키지 설치가 진행됩니다!!

**Comment by seong0929** [comment]
enter safe mode에서 import패키지가 없어요
- ![image](https://github.com/SeoulTechTCPGame/block-it/assets/50050003/c213cf3e-e4e8-404e-aa57-8d053a0f7797)
