### ISSUE TITLE
랭크

### ISSUE THREAD

**Issue by junnie082** [SeoulTechTCPGame/block-it#8]
- [ ] My profile 버튼 클릭시 나의 프로필 화면으로 이동
- [ ] 모든 플레이어의 랭크 및 프로필을 scrolling 을 통해 확인할 수 있음
- [ ] 한번 스크롤에 100명씩 확인 가능
- [ ] [더보기] 버튼을 누르면 다음 100명 확인 가능
- [ ] 랭크에 등록된 플레이어의 이름을 누르면 해당 플레이어의 프로필을 확인할 수 있음 (내 프로필과 동일한 형식의 프로필)

![Image](https://user-images.githubusercontent.com/88719152/234498340-64cd2ab3-f410-427c-9e5c-c4ee86fea3b8.png)

**Comment by seong0929** [comment]
임시 폐기
